name: .Deploy to Production
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version number to deploy'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.DEPLOY_KEY }}
    - name: "Setup Node.js"
      uses: "actions/setup-node@v1"
      with:
        node-version: 12
    - name: Bump version and push tag
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.DEPLOY_KEY }}
        git-message: 'Release {version}'
        git-user-name: 'warrensearle'
        git-user-email: 'warren@precise-minds.co.uk'
        tag-prefix: ''
        skip-on-empty: 'true'
        output-file: "false"

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}

    - name: Deploy
      run: echo Deploy everything to production
