name: .Changelog
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.DEPLOY_KEY }}
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
    - name: Output
      run: echo "Output = ${{ steps.changelog.outputs.changelog }}"
