
name: Close PR
'on':
  pull_request:
    types: [closed]
jobs:
  tests:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: conditional
        if: ${{ github.event.pull_request.merged == true }}
        run: echo This event is a PULL REQUEST MERGE.
