
name: Pull request
'on':
  pull_request:
    paths:
    - 'release-notes.md'
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: echo This is a Pull Request change

