name: Bump version
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.DEPLOY_KEY }}
    - name: Bump version and push tag
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.DEPLOY_KEY }}
        git-message: 'Bump version to {version}'
        git-user-name: 'warrensearle'
        git-user-email: 'warren@precise-minds.co.uk'
        tag-prefix: ''
        skip-on-empty: 'true'
        output-file: "false"
