name: Bump version
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: '0'
#     - name: Bump version and push tag
#       uses: anothrNick/github-tag-action@1.26.0
#       env:
#         GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
#         WITH_V: false

# jobs:
#   tag:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.DEPLOY_KEY }}

#       - name:  'Automated Github Action Version Bump'
#         uses:  'rimonhanna/gh-action-bump-version@master'
#         with:
#           tag-prefix:  ''

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.DEPLOY_KEY }}
    - name: Bump version and push tag
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.DEPLOY_KEY }}
        git-message: 'Bump version to {version}'
        git-user-name: 'warrensearle'
        git-user-email: 'warren@precise-minds.co.uk'
        tag-prefix: ''
        skip-on-empty: 'true'
        output-file: "false"
