
name: Firestore Rules
'on':
  pull_request:
    paths:
    - 'release-notes.md'
  push:
    branches:
      - main
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

