
name: Firestore Rules
'on':
  pull_request:
    paths:
    - 'release-notes.md'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc && npm ci
      - name: Lint check
        run: npm run lint-ci
