
name: Firestore Rules
'on':
  pull_request:
    paths:
    - 'release-notes.md'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm ci
      - name: Lint check
        run: npm run lint-ci
