name: "Bump Version"

'on':
  pull_request:
    types: [closed]

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        if: ${{ github.event.pull_request.merged == true }}
        uses: "actions/checkout@v2"
        with:
          ref: main
      - name: "Setup Node.js"
        if: ${{ github.event.pull_request.merged == true }}
        uses: "actions/setup-node@v1"
        with:
          node-version: 12
      - name: "Automated Version Bump"
        if: ${{ github.event.pull_request.merged == true }}
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          skip-tag:  'true'
          default: minor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
